### ISSUE TITLE
Error: Could not find dashboardHeader.

### ISSUE THREAD

**Issue by TarJae** [taylorperkins/Shiny-Dashboard-Template#2]

**Comment by TarJae** [comment]
Thank you taylorperkins for the elegant template. I tried to start the template many times. 
As I am new to r shiny it was not possible for me to run the template over weeks. Now with more knowledge I figured out the problem. 
Due to the fact that app.r, ui.r and server.R are in the parent directory I received the error: could not find dashboardHeader. 
Solution: after creating a new directory for ui.R and server.R and removing both from the parent directory, the app started without problems. Just add the new directory in the source part of the code. 
This may be trivial for advanced users, but for users who started to learn r shiny it is important!

**Comment by Makiavel974** [comment]
Hi,

You need to install and load the "shinydashboard" package before running the code;
